name: Quack Auto Build

on:
  push:
    branches:
      - main
      - master

  pull_request:

workflow_dispatch:

jobs:
  build:
    runs-on: windows-2025-vs2026

    strategy:
      matrix:
        config: [Release]
        platform: [x64]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2

      - name: Restore Packages
        run: nuget restore Quack.sln

      - name: Build Solution
        run: |
          MSBuild Quack.sln ^
            /p:Configuration=${{ matrix.config }} ^
            /p:Platform=${{ matrix.platform }}

      - name: Upload Build
        uses: actions/upload-artifact@v4
        with:
          name: Quack-Build
          path: |
            build/**/*.exe
            **/Release/**/*.exe
